package brainapi

import (
	"context"
	"strings"
	"time"
)

// TenantID identifies a project/tenant after binding resolution.
type TenantID string

// BindingKey is a surface-neutral key such as slack:channel:C123.
type BindingKey string

// JobID is a surface-neutral asynchronous work identifier generated by the gateway.
type JobID string

// Action describes a tenant-scoped operation checked by the gateway authorizer.
type Action string

const (
	// ActionCreateProject creates a new tenant and binding.
	ActionCreateProject Action = "create_project"
	// ActionQuery reads tenant content or metadata.
	ActionQuery Action = "query"
	// ActionDiscover reads tenant metadata only.
	ActionDiscover Action = "discover"
	// ActionIngest writes new source material into a tenant.
	ActionIngest Action = "ingest"
	// ActionStatus reads tenant-scoped job state.
	ActionStatus Action = "status"
	// ActionAdmin changes tenant lifecycle state.
	ActionAdmin Action = "admin"
)

// Principal is the surface-neutral identity created by an adapter.
type Principal struct {
	Source string
	ID     string
	Roles  []string
}

// Key returns a stable source-qualified identity key.
func (p Principal) Key() string {
	if p.Source == "" {
		return p.ID
	}
	return p.Source + ":" + p.ID
}

// HasRole reports whether the principal has role.
func (p Principal) HasRole(role string) bool {
	for _, r := range p.Roles {
		if strings.EqualFold(r, role) {
			return true
		}
	}
	return false
}

// SourceRef describes material already staged by a surface adapter.
type SourceRef struct {
	URI      string
	MimeType string
	Name     string
}

// Source describes a grounded source returned by query.
type Source struct {
	ID       string
	Title    string
	URI      string
	TenantID TenantID
}

// CreateProjectRequest asks the core to atomically provision a tenant.
type CreateProjectRequest struct {
	TenantID       TenantID
	BindingKey     BindingKey
	OwnerPrincipal Principal
	Metadata       map[string]string
}

// IngestRequest asks the core to enqueue source processing.
type IngestRequest struct {
	TenantID TenantID
	JobID    JobID
	Source   SourceRef
	Metadata map[string]string
}

// QueryRequest asks the core for grounded content synthesis.
type QueryRequest struct {
	TenantID TenantID
	Question string
	Options  map[string]string
}

// QueryResponse is a surface-neutral answer payload.
type QueryResponse struct {
	Answer             string
	Sources            []Source
	GroundedSpans      []string
	SupplementedSpans  []string
	GroundingAvailable bool
}

// DiscoverRequest asks for metadata-only discovery.
type DiscoverRequest struct {
	TenantID TenantID
	Query    string
}

// MetadataResult is a metadata-only discovery result.
type MetadataResult struct {
	ID      string
	Title   string
	Kind    string
	FreshAt time.Time
}

// DiscoverResponse contains metadata-only results. It must not contain source chunks.
type DiscoverResponse struct {
	Results []MetadataResult
}

// ProjectState controls whether a tenant can serve requests.
type ProjectState string

const (
	// ProjectOn allows tenant operations.
	ProjectOn ProjectState = "on"
	// ProjectOff freezes tenant operations while preserving data.
	ProjectOff ProjectState = "off"
)

// JobStatus is the core/control-plane shared asynchronous status enum.
type JobStatus string

const (
	// JobAccepted means the gateway accepted the job but core processing has not started.
	JobAccepted JobStatus = "accepted"
	// JobRunning means core workers are processing the job.
	JobRunning JobStatus = "running"
	// JobCompleted means processing succeeded.
	JobCompleted JobStatus = "completed"
	// JobFailed means processing failed.
	JobFailed JobStatus = "failed"
	// JobCheckRequired means callback/reconciliation could not establish a final state.
	JobCheckRequired JobStatus = "check_required"
)

// Final reports whether the status is terminal.
func (s JobStatus) Final() bool {
	return s == JobCompleted || s == JobFailed
}

// JobSnapshot is a tenant-scoped view of asynchronous work.
type JobSnapshot struct {
	TenantID  TenantID
	JobID     JobID
	Status    JobStatus
	ResultRef string
	Error     string
	UpdatedAt time.Time
}

// TenantInfo is an admin-surface metadata summary of a single tenant.
// It omits owner role details and chunk content to limit sensitive exposure.
type TenantInfo struct {
	TenantID  TenantID
	State     ProjectState
	OwnerID   string
	CreatedAt time.Time
}

// BindingInfo is an admin-surface summary of a single surface binding.
type BindingInfo struct {
	BindingKey BindingKey
	TenantID   TenantID
}

// SourceInfo is an admin-surface metadata summary of a source.
// It deliberately omits chunk text content.
type SourceInfo struct {
	ID        string
	TenantID  TenantID
	Name      string
	URI       string
	MimeType  string
	CreatedAt time.Time
}

// AdminListTenantsRequest enumerates all provisioned tenants.
// It carries no required fields; future versions may add pagination cursors.
type AdminListTenantsRequest struct{}

// AdminListTenantsResponse carries tenant summaries for all provisioned tenants.
type AdminListTenantsResponse struct {
	Tenants []TenantInfo
}

// AdminListBindingsRequest enumerates bindings.
// When TenantID is non-empty only bindings for that tenant are returned.
type AdminListBindingsRequest struct {
	TenantID TenantID // empty = all tenants
}

// AdminListBindingsResponse carries all matching binding summaries.
type AdminListBindingsResponse struct {
	Bindings []BindingInfo
}

// AdminListSourcesResponse carries source metadata summaries for a single tenant.
// Chunk content is never included.
type AdminListSourcesResponse struct {
	Sources []SourceInfo
}

// AdminListJobsResponse carries job snapshots for a single tenant.
type AdminListJobsResponse struct {
	Jobs []JobSnapshot
}

// Core is the platform data-core contract. Implementations must stay surface-neutral.
type Core interface {
	ResolveBinding(ctx context.Context, binding BindingKey) (TenantID, error)
	CreateProject(ctx context.Context, req CreateProjectRequest) error
	Ingest(ctx context.Context, req IngestRequest) error
	JobStatus(ctx context.Context, tenantID TenantID, jobID JobID) (JobSnapshot, error)
	Query(ctx context.Context, req QueryRequest) (QueryResponse, error)
	Discover(ctx context.Context, req DiscoverRequest) (DiscoverResponse, error)
	SetProjectState(ctx context.Context, tenantID TenantID, state ProjectState) error

	// Admin read operations — callers must hold ActionAdmin.
	// Implementations use the admin sentinel (GUC '*' in Postgres, or full map
	// access in memory) to enumerate across tenants without checking project state.

	// AdminListTenants returns metadata summaries for all provisioned tenants.
	AdminListTenants(ctx context.Context, req AdminListTenantsRequest) (AdminListTenantsResponse, error)

	// AdminListBindings returns binding summaries, optionally filtered by tenant.
	AdminListBindings(ctx context.Context, req AdminListBindingsRequest) (AdminListBindingsResponse, error)

	// AdminListSources returns source metadata for a specific tenant (no chunk content).
	// The implementation must not check project state.
	AdminListSources(ctx context.Context, tenantID TenantID) (AdminListSourcesResponse, error)

	// AdminListJobs returns job snapshots for a specific tenant.
	// The implementation must not check project state.
	AdminListJobs(ctx context.Context, tenantID TenantID) (AdminListJobsResponse, error)

	// AdminGetJob returns a single job snapshot for the given tenant and job.
	// The implementation must not check project state.
	AdminGetJob(ctx context.Context, tenantID TenantID, jobID JobID) (JobSnapshot, error)
}
