package brainapi

import "strings"

// ValidateBindingKey checks the surface-neutral binding-key shape.
func ValidateBindingKey(key BindingKey) error {
	const op = "validate_binding_key"
	parts := strings.Split(string(key), ":")
	if len(parts) != 3 {
		return invalidf(op, "binding key must have form surface:kind:id")
	}
	for _, part := range parts {
		if strings.TrimSpace(part) == "" || strings.ContainsAny(part, " \t\n\r") {
			return invalidf(op, "binding key parts must be non-empty and whitespace-free")
		}
	}
	return nil
}

// ValidateTenantID checks tenant identifiers generated by the gateway.
func ValidateTenantID(id TenantID) error {
	const op = "validate_tenant_id"
	if strings.TrimSpace(string(id)) == "" {
		return invalidf(op, "tenant id is required")
	}
	if strings.ContainsAny(string(id), " \t\n\r") {
		return invalidf(op, "tenant id must be whitespace-free")
	}
	return nil
}

// ValidateJobID checks gateway-generated job identifiers.
func ValidateJobID(id JobID) error {
	const op = "validate_job_id"
	if strings.TrimSpace(string(id)) == "" {
		return invalidf(op, "job id is required")
	}
	if strings.ContainsAny(string(id), " \t\n\r") {
		return invalidf(op, "job id must be whitespace-free")
	}
	return nil
}
